/* Ghost Match card library.
   Every spell is a real Chris Pachulski project/experience reskinned as an Izzet card.
   Opponent is "The Deadlines" — mono-W/B bureaucracy deck.
   Mana cost notation: 'U' blue, 'R' red, 'W' white, 'B' black, number = generic. */

export const CARDS = {
  /* ─── Chris's Izzet deck ──────────────────────────────────────── */
  'pacific-ocean': {
    id: 'pacific-ocean',
    name: 'Pacific Data Ocean',
    type: 'Basic Land — Island',
    colors: ['U'],
    isLand: true,
    produces: ['U'],
    flavor: '"Where messy data goes to be decided upon."',
    art: 'ocean',
  },
  'do-droplet': {
    id: 'do-droplet',
    name: 'Digital Ocean Droplet',
    type: 'Basic Land — Mountain',
    colors: ['R'],
    isLand: true,
    produces: ['R'],
    flavor: '"Running 24/7 since 2017."',
    art: 'volcano',
  },
  'snowflake': {
    id: 'snowflake',
    name: 'Snowflake Warehouse',
    type: 'Land — Izzet Dual',
    colors: ['U', 'R'],
    isLand: true,
    produces: ['U', 'R'],
    flavor: '"Role-based warehouse routing. Enters untapped."',
    art: 'dual',
  },
  'bigquery': {
    id: 'bigquery',
    name: 'BigQuery Workspace',
    type: 'Basic Land — Island',
    colors: ['U'],
    isLand: true,
    produces: ['U'],
    flavor: '"gaeas-cradle. Partitioned by dt."',
    art: 'ocean',
  },
  'toolkit': {
    id: 'toolkit',
    name: 'R & Python Toolkit',
    cost: ['1', 'U'],
    type: 'Creature — Utility Construct',
    colors: ['U'],
    power: 2, toughness: 1,
    abilities: ['Haste'],
    text: 'Haste. When ~ enters, scry 2.',
    flavor: '"One import, four integrations."',
    art: 'construct',
  },
  'ghscope': {
    id: 'ghscope',
    name: 'Ghscope',
    cost: ['1', 'U'],
    type: 'Instant',
    colors: ['U'],
    text: 'Scry 3.',
    flavor: '"Know a repo before you depend on it."',
    art: 'lens',
  },
  'claude-code': {
    id: 'claude-code',
    name: 'Claude Code',
    cost: ['1', 'U', 'R'],
    type: 'Sorcery',
    colors: ['U', 'R'],
    text: 'Draw two cards. ~ deals 3 damage to any target.',
    flavor: '"AI did exactly what you asked — plus six things you didn\'t."',
    art: 'spark',
  },
  'mtgban': {
    id: 'mtgban',
    name: 'MTGBAN',
    cost: ['1', 'U', 'R'],
    type: 'Legendary Artifact Creature — Engine',
    colors: ['U', 'R'],
    power: 4, toughness: 4,
    abilities: [],
    text: "When ~ enters, it deals 6 damage to target opponent. (One for each year, minus the two we haven't shipped yet.)",
    flavor: '"$1.2M annually. 500+ paying subscribers. 8 years."',
    art: 'engine',
    legendary: true,
  },
  'counterflux': {
    id: 'counterflux',
    name: 'Counterflux',
    cost: ['U', 'U'],
    type: 'Instant',
    colors: ['U'],
    text: 'Counter target spell. ~ cannot be countered.',
    flavor: '"Stack of docs. clarity → dream → session-sounds."',
    art: 'swirl',
  },
  'wizards-of-the-coast': {
    id: 'wizards-of-the-coast',
    name: 'Wizards of the Coast',
    cost: ['2', 'U', 'R'],
    type: 'Legendary Enchantment — Guild',
    colors: ['U', 'R'],
    text: 'Creatures you control get +3/+3 and gain haste and trample.',
    flavor: '"Senior Data Scientist. November 2025."',
    art: 'guild',
    legendary: true,
  },

  /* ─── Opponent deck: The Deadlines ────────────────────────────── */
  'another-meeting': {
    id: 'another-meeting',
    name: 'Another Meeting',
    type: 'Basic Land — Plains',
    colors: ['W'],
    isLand: true,
    produces: ['W'],
    flavor: '"This could have been an email."',
    art: 'plains',
  },
  'legacy-spreadsheet': {
    id: 'legacy-spreadsheet',
    name: 'Legacy Spreadsheet',
    type: 'Basic Land — Swamp',
    colors: ['B'],
    isLand: true,
    produces: ['B'],
    flavor: '"Tabs. Within tabs. Within tabs."',
    art: 'swamp',
  },
  'scope-creep': {
    id: 'scope-creep',
    name: 'Scope Creep',
    cost: ['1', 'W'],
    type: 'Creature — Specter',
    colors: ['W'],
    power: 1, toughness: 1,
    text: 'Whenever ~ attacks, defending player adds one unplanned feature.',
    flavor: '"Just one more small thing."',
    art: 'creep',
  },
  'meeting-overrun': {
    id: 'meeting-overrun',
    name: 'Meeting Overrun',
    cost: ['2', 'W'],
    type: 'Creature — Committee',
    colors: ['W'],
    power: 3, toughness: 3,
    text: 'Combat will resume sometime later.',
    flavor: '"We\'ll circle back."',
    art: 'committee',
  },
  'red-tape': {
    id: 'red-tape',
    name: 'Red Tape',
    cost: ['W', 'W'],
    type: 'Instant',
    colors: ['W'],
    text: 'Counter target spell that requires approval.',
    flavor: '"Who approved this?"',
    art: 'tape',
  },
  'undocumented-script': {
    id: 'undocumented-script',
    name: 'Undocumented Script',
    cost: ['2', 'B'],
    type: 'Creature — Horror',
    colors: ['B'],
    power: 4, toughness: 4,
    text: 'Nobody knows how ~ works and we cannot remove it.',
    flavor: '"It runs. That\'s enough."',
    art: 'horror',
  },
};

/* Convenience: unique instance id for each physical card on the table.
   Same card can appear twice (e.g., two Plains) and needs separate refs. */
export function inst(cardId, tag = '') {
  return `${cardId}${tag ? `#${tag}` : `#${Math.random().toString(36).slice(2, 7)}`}`;
}
